site_name: ichrome

theme:
  name: "material"

nav:
  - index.md
  - quickstart.md
  - cmd.md
  - reference:
      - base: "reference/base.md"
      - AsyncTab: "reference/AsyncTab.md"
      - AsyncChromeDaemon: "reference/AsyncChromeDaemon.md"
      - AsyncChrome: "reference/AsyncChrome.md"
      - Debugger: "reference/Debugger.md"
      - WebAPP: "reference/WebAPP.md"
plugins:
  - mkdocstrings
